[Service]
ExecStart=
ExecStart=/usr/bin/docker compose -f /opt/crystal-baseball/current/compose.yaml -f /opt/shotrax/current/integration/crystal-baseball.override.yaml up -d --remove-orphans
ExecStop=
ExecStop=/usr/bin/docker compose -f /opt/crystal-baseball/current/compose.yaml -f /opt/shotrax/current/integration/crystal-baseball.override.yaml down
